apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
  namespace: keda-demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: worker-service
  endpoints:
    - port: "8080"
      path: /actuator/prometheus
      interval: 10s
  namespaceSelector:
    matchNames:
      - keda-demo
